### ISSUE TITLE
badge colors

### ISSUE THREAD

**Issue by pathia** [Nerwyn/material-rounded-theme#1]
I really like the looks of this theme. But I don't like the badge colors in a picture-element card. They look a bit pinky instead of red.
![afbeelding](https://github.com/Nerwyn/material-rounded-theme/assets/126187/08aba98d-8df1-4319-a4b3-bad92d9ded8f)

Also, in light mode I cannot see the upper navigation bar. See attached screenshot.
![afbeelding](https://github.com/Nerwyn/material-rounded-theme/assets/126187/499bec5d-5207-4390-b5b6-6479d7b569ce)

Can I edit these things somehow without modifying your theme yaml ? Because that would give me issues whenever I update the theme.

**Comment by pathia** [comment]
What I tried to show in the second screenshot is the top right when in edit mode. I can show you more but it's all blurred like in the screenshot. When switching back to the HA default in blue I can see everything clear.
Also, thanks for the fast badge fixing. I will try to update it in hacs.

**Comment by Nerwyn** [comment]
Ah I see now, it was so washed out in the screenshot that I couldn't see the views or done button. This may be a caching issue as this is what it looks like in light view for me:

![image](https://github.com/Nerwyn/material-rounded-theme/assets/43071698/15f852ba-764a-441e-af4a-e02a7d8f50ca)

Also, this theme turns the header toolbar into a footer, so if it still appearing at the top of the screen (and you have card-mod installed) then you definitely need to refresh or clear cache.

**Comment by pathia** [comment]
I tried and with card mod installed it looks better in respect to the colors but I don't want the header at the footer 😄 
I guess that can not be made configurable, right ? That would make for a general solution.

**Comment by Nerwyn** [comment]
I can make it configurable in the sense that I can include a copy of the theme that doesn't have the card-mod section, and then work on fixing the colors of it. I'll try to work on it later tonight.

**Comment by Nerwyn** [comment]
Can you try [1.4.0-beta.006](https://github.com/Nerwyn/material-rounded-theme/releases/tag/1.4.0-beta.006)? It should fix the toolbar colors when card-mod isn't used, and adds a "no mod" version.

**Comment by pathia** [comment]
Seems to work indeed. I tried the nomod version. The badges are now red but with white text font so they look empty now 🤔
The toolbar looks readable now 👍

**Comment by Nerwyn** [comment]
That might really be a caching issue this time, because the text is black for me. Can you try hard refreshing (Ctrl + F5)?
![image](https://github.com/Nerwyn/material-rounded-theme/assets/43071698/76323155-f66a-4231-a4dd-f5309af981d1)

**Comment by pathia** [comment]
Unfortunately it doesn't help. It's in both Firefox and Chrome. But I think I'll stick to the default theme. I got really used to it after four years of using the default blue HA theme 😃

**Comment by Nerwyn** [comment]
Fixed in [1.4.0](https://github.com/Nerwyn/material-rounded-theme/releases/tag/1.4.0)
