### ISSUE TITLE
Allow background image

### ISSUE THREAD

**Issue by jurgenf** [Nerwyn/material-rounded-theme#10]
**Is your feature request related to a problem? Please describe.**
Currently if a background is defined in de Lovelace config e.g.
`background: center / cover no-repeat url(/local/wallpaper.jpg)`
The background is not visibile

**Describe the solution you'd like**
Allow the background to render behind the view. Either always or as a sub-theme.

**Describe alternatives you've considered**
I tried using card-mod but since the background is outside the card scope it is hard to do.

**Additional context**
I do understand the theme is meant to reflect the Google Home look and feel, however there might be a use-case for allow a background image to be (partly) visible.

**Comment by Nerwyn** [comment]
It's working for me

![image](https://github.com/Nerwyn/material-rounded-theme/assets/43071698/4913072f-323f-4715-bacb-e64e481ec805)

**Comment by jurgenf** [comment]
Hmm, it seems that it only triggers if the theme is set in the view configuration. It does work if the theme is set in the user profile. Might not be worth it to fix then.

**Comment by Nerwyn** [comment]
My theme is only set in the user profile.
