### ISSUE TITLE
The bottom bar will not move down

### ISSUE THREAD

**Issue by cooltings** [Nerwyn/material-rounded-theme#11]
**Checklist:**

-   [ X] I updated to the latest version available
-   [ X] I cleared the cache of my browser

**Release with the issue:**
latest

I have tried multiple browsers but cannot seem to get the bar to move down even if I install manually

**Comment by Nerwyn** [comment]
Do you have card-mod installed? What does the toolbar look like? Are the card-mod changes partially applied or not at all?

**Comment by Nerwyn** [comment]
Closed due to lack of response.
