### ISSUE TITLE
Dynamic base color

### ISSUE THREAD

**Issue by Sprocket02** [Nerwyn/material-rounded-theme#12]
The base color of the Material You can be set or adjusted depending on the selected background image. Wouldn't it be cool to adopt this here in HA as well?

![Screenshot_20240427-071321](https://github.com/Nerwyn/material-rounded-theme/assets/37394766/822dd1d9-93c4-428b-8f67-12facea41620)

**Comment by Nerwyn** [comment]
Someone asked about this on the community forums but I forgot about it since an issue was never made here. The Android companion app does have an optional sensor for the accent color, in my case `sensor.pixel_fold_accent_color`. I could use card mod to detect this (or a helper sensor that points to this sensor and have instructions on how to create the helper and activate this sensor) and use it as the accent color, but I'd also have to include a way to calculate the primary color from that. This would also prove problematic when you have multiple users who want their own accent colors.

**Comment by Sprocket02** [comment]
Thanks for the feedback. Does it make sense to put a feature request in the companion app first?

**Comment by Nerwyn** [comment]
For iPhone maybe. For Android I think we have what we need to get started. I'll try to come back to this later this week.

**Comment by Nerwyn** [comment]
I've got some decent progress thus far in a new branch called [material-you](https://github.com/Nerwyn/material-rounded-theme/blob/material-you/themes/material_rounded.yaml#L217). I'm able to use card-mod to get a user defined sensor and use it as a color, and I implemented a hex to rgb to hsl calculation in jinja2.

Now I need to figure out how to calculate a good primary color from the user provided accent color. I think I can also add global vs user specific colors using user IDs.

**Comment by Nerwyn** [comment]
I've got accent and primary colors generating from a user provided hex color working and they replace the colors in the toolbar. But it doesn't seem like it's applying anywhere else. I need to figure out why and if it's possibly for these values to override the accent and primary colors globally.

**Comment by Nerwyn** [comment]
Good news: I got user definable colors working on the dashboards for any cards that use accent or primary color.

Bad news: It doesn't seem like card-mod themes apply to more info popups or the services and settings pages. This severely limits what I can make user configurable using card-mod and templates.

**Comment by Nerwyn** [comment]
Got it working in more info popups but not services and settings.

**Comment by Nerwyn** [comment]
@Sprocket02 I've created [an alpha build](https://github.com/Nerwyn/material-rounded-theme/releases/tag/2.0.0-alpha.001) that allows you to set the theme primary and accent colors using sensors. Instructions on how are in the [branch README](https://github.com/Nerwyn/material-rounded-theme/tree/material-you?tab=readme-ov-file#material-you-colors).

It doesn't change all of the UI colors since the Google Home app still uses static colors and doesn't work on all pages due to card-mod limitations, but it's a start.

**Comment by Sprocket02** [comment]
Very cool, thank you very much! I will test it immediately!

**Comment by Sprocket02** [comment]
Can you perhaps send me a code snippet to create the template sensor? To be honest, I haven't understood it.

_This theme supports Material You color theming! Create a helper template sensor named Material Rounded Base Color that returns the hex code of your preferred base color..._

**Comment by Nerwyn** [comment]
I'm also going to work on a more true to Material You version of this theme. As it is now, Material Rounded is based on the Google Home and Play apps, which use Material 3 shapes but not color styles. Here are some screenshots of some Google apps that do use Material You colors that I'm going to work off of.

<img width="200" src="https://github.com/Nerwyn/material-rounded-theme/assets/43071698/75a42b52-16d0-4c73-bab2-96fcb160df1b"/>
<img width="200" src="https://github.com/Nerwyn/material-rounded-theme/assets/43071698/d4e74e2a-26a4-4e11-8133-c15262ea6189"/>
<img width="200" src="https://github.com/Nerwyn/material-rounded-theme/assets/43071698/b6e1d0fd-35bf-4dfb-b402-bbd8e16584b3"/>
<img width="200" src="https://github.com/Nerwyn/material-rounded-theme/assets/43071698/b5dbff4f-2fd9-4528-a77e-3321b49b4b71"/>
<img width="200" src="https://github.com/Nerwyn/material-rounded-theme/assets/43071698/6c70b92a-94a5-4ddc-9af8-93ab395588d0"/>
<img width="200" src="https://github.com/Nerwyn/material-rounded-theme/assets/43071698/d0f4b6d2-78d5-41fe-9bca-67642de61164"/>
<img width="200" src="https://github.com/Nerwyn/material-rounded-theme/assets/43071698/e357bb56-c336-4145-af41-83f9d4739cc8"/>
<img width="200" src="https://github.com/Nerwyn/material-rounded-theme/assets/43071698/91a21df9-2c59-4579-a4bf-6c461b879f4a"/>

As you can see Google isn't entirely consistent in how Material You colors are used in apps that support it so I won't feel too bad about taking my own creative liberties. I'm going to aim for the

**Comment by Sprocket02** [comment]
For the installation I only have to replace the material_rounded.yaml from the Alpha build, right? Somehow it still doesn't work properly for me. I can select the theme but I can't change any colors via the helper.

There is a typo in your description of how to create the helper. There you write that you should create a helper with the name Material Rounded Theme Color. But it must be called Material Rounded Base Color or?

**Comment by Nerwyn** [comment]
You should be installing it via HACS. If you replace the file directly you also have to run the service `frontend.reload_themes`. And sorry! It should be `Material Rounded Base Color` I've fixed the README.

**Comment by Sprocket02** [comment]
Now it works. Super cool. Thanks a lot!

**Comment by Nerwyn** [comment]
I've created another version of the theme that changes almost all colors using a user given base color but it's not great. Calculating a good Material You color palette has proven difficult and card-mod in themes can't add styles to many parts of Home Assistant. I'm going to have shelve further work on this for a while because it's giving me a headache.

**Comment by Nerwyn** [comment]
I've done a huge refactor to make this theme easier to develop using separate reusable CSS style files and a pre-commit build pipeline and put out the first version 2 beta for Material You primary/accent colors and components. The Material You full color version of the theme will no longer appear but has been saved to a separate untouched base theme file for a future version 3. I hope to release version 2 soon and come back to the full color version 3 theme at a later time.

**Comment by mousemat86** [comment]
looking forward to this version. I spent the last few days tweaking the theme with a wider colour selection, however I will stop now at await the release! 

thanks for your work on this theme

**Comment by Nerwyn** [comment]
Can y'all give v2 beta 4 a try? I made all the card-mod CSS selectors as specific as possible to cut down on load times and removed a lot of redundant/unnecessary styles.

**Comment by mousemat86** [comment]
Hey Nerwyn I've been using the latest beta of the theme, it's looking great. 

Not sure if you're seeing this but some URLs in HACs don't have great legibility, I've attached a grab here. 

![Screenshot_20240603-023220](https://github.com/Nerwyn/material-rounded-theme/assets/57290277/336ebb28-374f-4c34-8990-e5cd4951b7c2)

Also saw you're using a fire tablet. Is there an easy way reduce the action items to three dots, same as mobile? I use a fire tablet 8 and find all 3 action items too cluttered on the dashboard. Might not be possible with card mod?

**Comment by Nerwyn** [comment]
I've set `linked-text-color` to `primary-color` in the latest v2 beta, it should be more visible now.

Kebab menu (three dots) vs three action items is determined by screen size, specifically at widths greater than 870px it shows three menu items, and at smaller widths it condenses them to the kebab menu. It looks like Home Assistant isn't simply hiding and showing elements with styles and media queries, but is rendering different elements at different resolutions. AFAIK there wouldn't be a way to display the kebab menu at higher resolutions.

I've personally retired most of my fire tablets in favor of [this](https://community.home-assistant.io/t/is-this-the-perfect-standalone-tablet-for-ha/658422) (I was the one who got the flash process working on Windows!).

**Comment by Nerwyn** [comment]
Officially released [v2.0.0](https://github.com/Nerwyn/material-rounded-theme/releases/tag/2.0.0)!

But! I still need to come back to create the full color theme for v3, which I'll do at a later time since v2 took so long. I'll leave this issue open until then.

**Comment by xvlw** [comment]
This looks great, i'm excited for the potential feature request and v3

I've converted from my custom theme over to this as of v2

Thanks for everything you do man!

**Comment by mcsdodo** [comment]
Any chance the base color sensor reading stopped working? I've installed from Hacs, I have a sensor but cannot see any changes.

**Comment by Nerwyn** [comment]
Still working for me and I'm up to date. What's the name and entity ID of your sensor?

**Comment by mcsdodo** [comment]
I have `sensor.material_rounded_base_color` as per documentation. Template `{{ states('sensor.material_rounded_base_color') }}` outputs `#ff9800` yet dashboard looks like this 
![image](https://github.com/Nerwyn/material-rounded-theme/assets/1957524/d0807ebf-0728-46e1-8b3f-1445f68927c1)

**Comment by Nerwyn** [comment]
Still working for me and I'm up to date. What's the name and entity ID of your sensor?Do you have card-mod installed?

**Comment by mcsdodo** [comment]
Yes that was it. I made a PR https://github.com/Nerwyn/material-rounded-theme/pull/20

**Comment by Nerwyn** [comment]
Finally getting back around to this. I've managed to create a separate JavaScript module that can be added as a resource to Home Assistant for generated true Material You color themes. I've also updated the theme to use this module's CSS variables instead of the hacky approximation in V2. More information can be found [in this alpha](https://github.com/Nerwyn/material-rounded-theme/releases/tag/3.0.0-alpha.002) and the [v3 branch README](https://github.com/Nerwyn/material-rounded-theme/tree/v3?tab=readme-ov-file#material-rounded-theme).

From my testing it's working great, and applies to all of Home Assistant consistently! I'm going to work on the true Material Design 3 version of the theme next.

**Comment by Nerwyn** [comment]
Material You color theme has been created and is working great with use color sensors. I still have to tweak the colors used to improve how it looks.

**Comment by Nerwyn** [comment]
The Material You theme, accurate user color theme generation, and other updates are now in beta. From what I've compared to so far it looks just like Android apps and websites that use Material Design 3, and the colors used in both are exactly the same.

https://github.com/Nerwyn/material-rounded-theme/releases/tag/3.0.0-beta.002

**Comment by Nerwyn** [comment]
Released [3.0.0](https://github.com/Nerwyn/material-rounded-theme/releases/tag/3.0.0).

This theme now has accurate material design 3 color theming via the [material color utilities](https://github.com/material-foundation/material-color-utilities) module. This is a breaking change as it requires a JavaScript module resource to be added to your Home Assistant instance, but it's worth it! See the README for screenshots how how Home Assistant can now perfectly match your Android Material You apps.
