### ISSUE TITLE
Transparent Selection 

### ISSUE THREAD

**Issue by whyisthisbroken** [Nerwyn/material-rounded-theme#13]
I love this theme and would also use the transparent option.
However, one thing should be changed: the selection window is unreadable...

![Screenshot 2024-04-27 100705](https://github.com/Nerwyn/material-rounded-theme/assets/96284773/9f108aff-eb91-42e9-9403-ac9107f4500b)
![Screenshot 2024-04-27 100746](https://github.com/Nerwyn/material-rounded-theme/assets/96284773/7691772f-2e2f-4b97-b5af-6e497a5924ef)

**Comment by Nerwyn** [comment]
Per the README, `Material Rounded Transparent Card` was made to be used at the card level to give cards transparent backgrounds. If used for the user theme the transparent background will cause issues like this.

That being said, the transparent background is also causing issues with dropdowns in dashboards, so I should consider changing the card backgrounds from transparent to being the same as the actual background.

**Comment by whyisthisbroken** [comment]
Ah okay. Thanks for the quick Response.
Keep it up - best Theme so far for HA.

**Comment by Nerwyn** [comment]
Thanks! But I also said that I can possibly fix this so I'm going to reopen it and implement a quick fix for you to test. So far it's working fine from my end.

**Comment by Nerwyn** [comment]
Can you try the latest beta? It should fix the issue.

**Comment by whyisthisbroken** [comment]
I'll try it tomorrow - at the moment i'm not at home. If anything goes wrong it's not good 😅

I'll give u feedback tomorrow. ✌️

**Comment by whyisthisbroken** [comment]
What should i say.... perfect :)

![image](https://github.com/Nerwyn/material-rounded-theme/assets/96284773/39022818-3617-444b-8010-5977c53c5d11)

**Comment by Nerwyn** [comment]
It looks like the new label field uses the CSS variable `--background-color`. It may be that I don't need to set this variable at all. Also, should I make a transparent card version of this theme that also has the bottom Google Home style toolbar?

**Comment by whyisthisbroken** [comment]
That would be nice - maybe like the other choice, with or without mods... 
- Material Rounded
- Material Rounder without Mods
- Material Rounder Transp. 
- Matarial Rounden Transp. without Mods.

**Comment by Nerwyn** [comment]
1.5.4-beta.003 has four versions of the theme with and without card-mod, and removes `--background-color`. `+ Choose label` now shows up as white.

I don't think changing the weather icons is something I can / am going to do. Home Assistant themes use yaml to define custom css variables, so `weather-icon-clear-night` would be `--weather-icon-clear-night` in CSS.

**Comment by whyisthisbroken** [comment]
Looks good, now it's all readable. 👍🏻 
Thanks for the quick fixes...

**Comment by Nerwyn** [comment]
If it all looks good I'll go ahead and release it.

**Comment by Nerwyn** [comment]
Fixed in [1.5.4](https://github.com/Nerwyn/material-rounded-theme/releases/tag/1.5.4)
