### ISSUE TITLE
The navigation bar shrinks after using navigate in lovelace.

### ISSUE THREAD

**Issue by deezid** [Nerwyn/material-rounded-theme#15]
Latest version 1.6 installed, but was an issue with older versions, too.

I'm using the navigate function to other lovelace pages on some chip or mushroom cards and whenever I go back the navigation bar on the bottoms shrinks horizontally as shown in the video.
https://github.com/Nerwyn/material-rounded-theme/assets/98790344/a615f87c-46da-4ca4-985d-3bb8c94b574f

The problem shows on Chrome on Mac, Home Assistant App on Mac, Chrome on Android and Home Assistant app on Android.

**Comment by Nerwyn** [comment]
Are you on the latest version of card-mod? Card-mod styles not fully applying to the toolbar was an issue before version 3.4.0 but I thought it was fixed.

**Comment by deezid** [comment]
Yes, 3.4.3 is installed over here.
Should I try downgrading to 3.4.0?

The bar looks correct initially but shrinks whenever navigate is used...

**Comment by Nerwyn** [comment]
That's weird, I can't recreate it on any of my devices. Downgrading shouldn't be necessary since I'm also on 3.4.3.

I do see the toolbar tabs briefly left aligned before card-mod fully applies. Maybe card-mod isn't reapplying on page load for some reason? Do you have [card-mod installed as a resource](https://github.com/thomasloven/lovelace-card-mod?tab=readme-ov-file#performance-improvements)?

**Comment by deezid** [comment]
I just set card-mod as a ressource now but I don't see any difference in behaviour. 
Checked ressources to make sure.

**Comment by deezid** [comment]
Found a workaround for Chroma and Home Assistant apps.
If I don't use the navigation to go back at the bottom (as shown in video) but rather the browser ui or phone gestures to navigate, the navigation bar will be fine.

**Comment by Nerwyn** [comment]
I started intermittently running into this issue too. I think it's because card-mod is making so many style changes that they're not all applying consistently. I still have some ideas for how I might be able to mitigate this with refactors but no promises that it'll actually work.

**Comment by Nerwyn** [comment]
Bad news - the idea didn't work. I'm not sure there's a fix to this unless card-mod's performance is improved.

**Comment by deezid** [comment]
Thinking of making these subviews regular again or putting on another dashboard instead, which also fixes the issue.

**Comment by Nerwyn** [comment]
Can you try v2 beta 4 and see if it makes a difference?

**Comment by deezid** [comment]
Tried the latest beta, refreshed but it still shrinks after using subviews sadly

**Comment by Nerwyn** [comment]
The big problem is that the entire `ha-tabs/paper-tabs` element gets unloaded in subviews, which causes the card-mod CSS to unload. I don't think there's a way around this without a fix to card-mod itself.

**Comment by Jejebond** [comment]
Is this issue linked to this (Bottom bar not loaded properly) ? Reloading fix the problem but it keeps appearing uncentered randomly.

![Screenshot_20240601-183058](https://github.com/Nerwyn/material-rounded-theme/assets/3942165/e3bf6b55-de87-4b44-b554-fda904645111)

**Comment by Nerwyn** [comment]
Yup. Is that after viewing a sub view? It's a card mod issue where styles within a shadow-root are lost when an element unloads. I don't think there's anything I can do about it

**Comment by Nerwyn** [comment]
@deezid @Jejebond can y'all try the latest v2 beta (10 at time of writing). I did some out of the box thinking (the box being the `ha-tabs`, `paper-tabs`, and `paper-tab` shadow-roots that weren't loading their styles properly 😁) and managed to create very similar styles for the view tabs without the shadow-roots. They seem to be applying correctly after leaving a subview and I imagine shouldn't not load anymore due to shadow-root style slowness.

**Comment by Jejebond** [comment]
@Nerwyn I'll try this out during 24h just to make sure and give you feeback tomorrow. For now on, it seems to be working.

**Comment by Nerwyn** [comment]
Note - Subviews must be placed as the last view tabs on the toolbar for the view tab size calculation to be correct, otherwise they won't be skipped when counting view tabs.

**Comment by deezid** [comment]
Latest version indeed seems to have it fixed. 
Also way less jumpiness when loading the dashboard the very first time 😀

**Comment by Jejebond** [comment]
It only happen once to me but it's much more stable ! Is it normal that the menu and 3 dot buttons are up now ? (i'm fin with this look, much better).

**Comment by Nerwyn** [comment]
The fact that it happened once is concerning but I'm hoping that was a cache issue 🙃.

The menu buttons at the top is the new normal!  They've been moved to better follow the material design 3 guidelines and give more room for view tabs. These buttons are part of the [top app bar](https://m3.material.io/components/top-app-bar/overview) and should be separate from the [navigation bar](https://m3.material.io/components/navigation-bar/overview). I didn't want to take even more room away from the view window so I made them overlays that disappear on scroll. Users can opt to create their own top app bar using something like markdown card button-card if they don't want them to overlay, kind of like I do in the updated screenshots.

**Comment by Nerwyn** [comment]
Released [v2.0.0](https://github.com/Nerwyn/material-rounded-theme/releases/tag/2.0.0).
