### ISSUE TITLE
Text not readable / Text or Background Color adjustment

### ISSUE THREAD

**Issue by whyisthisbroken** [Nerwyn/material-rounded-theme#16]
**Checklist:**

-   [X] I updated to the latest version available
-   [X] I cleared the cache of my browser

**Browser and Operating System:**
Chrome latest

**Description of problem:**
Color / Text not readable. The Dark Blue is "Condition not passed"
Condition passed on Green is readable

![Test Not passed](https://github.com/Nerwyn/material-rounded-theme/assets/96284773/da4b8888-8e54-4f36-9097-8ade5ede9a59)
![Test passed](https://github.com/Nerwyn/material-rounded-theme/assets/96284773/2ab90e82-c2a9-45a9-9672-f942882f718d)

**Comment by Nerwyn** [comment]
It looks like this is because `text-primary-color` uses the same value as `accent-color`. I'll have to see where else `text-primary-color` is used to make sure changing it won't make something else look bad.

![image](https://github.com/Nerwyn/material-rounded-theme/assets/43071698/4315d98e-8577-43dc-bebb-84ae4419b28a)

**Comment by Nerwyn** [comment]
Fixed in [1.6.1](https://github.com/Nerwyn/material-rounded-theme/releases/tag/1.6.1).

**Comment by Nerwyn** [comment]
@whyisthisbroken I think I'm going to have to revert this. It breaks the display of the add card button and calendar.
![image](https://github.com/Nerwyn/material-rounded-theme/assets/43071698/e74e4bba-2629-4272-bc4a-af22c9592149)

![image](https://github.com/Nerwyn/material-rounded-theme/assets/43071698/938594d0-262e-4279-a354-1d6f5455f5f1)

**Comment by Nerwyn** [comment]
Found a better solution - use `lovelace-background` for `text-primary-color)`.
![image](https://github.com/Nerwyn/material-rounded-theme/assets/43071698/63a5121a-c980-491e-9061-353d85bee5e1)
![image](https://github.com/Nerwyn/material-rounded-theme/assets/43071698/47941722-e7a1-4d8e-8d9d-c993fabff710)
![image](https://github.com/Nerwyn/material-rounded-theme/assets/43071698/57522767-34ed-43ad-99c4-b8b399671831)
Seems to also work in light mode, although for some reason the CSS of the add card button is different.

**Comment by Nerwyn** [comment]
Released [1.6.2](https://github.com/Nerwyn/material-rounded-theme/releases/tag/1.6.2).
