### ISSUE TITLE
Can't see dropdown text in History time period selection

### ISSUE THREAD

**Issue by jeffm999** [Nerwyn/material-rounded-theme#2]
great them , plan to use it from now on, but problem is with text visibility in **History** period selection :

![image](https://github.com/Nerwyn/material-rounded-theme/assets/49336389/102a16b9-ac98-422f-9c0f-c4db0ff52b1c)

the dropdown test is almost invisible, compared to default theme :+1: 

![image](https://github.com/Nerwyn/material-rounded-theme/assets/49336389/31349bbe-a430-481b-a3ba-c7df61518658)

It would be nice if the text was darker. 
I looked at the theme yaml , but I could not work out which  color variable to change!

rgds, jeff

**Comment by Nerwyn** [comment]
Can you try [1.4.0-beta.006](https://github.com/Nerwyn/material-rounded-theme/releases/tag/1.4.0-beta.006) and let me know if it fixes the issue? I tweaked the primary, accent, and text colors among other things and I think it should fix your issue.

**Comment by jeffm999** [comment]
yep , thanks . fixes my issue with History droplist, I'll close in github
after I've had time to test other screens

rgds
