### ISSUE TITLE
Cards jumping in Section View

### ISSUE THREAD

**Issue by currydani** [Nerwyn/material-rounded-theme#21]
Hi, 
First of all i love this theme, incredible work. 
But i started playing with the new section view layout for the dashboard, and i noticed, that if i change views, the cards reorient to the top (probably since there is no header i guess). This only appears with the section layout, if i change back to any other, its not present. It also only shows with the material rounded theme (with the header mod). Is this something that could be looked into, or is this a problem with the section view in general?
I would love to keep using this theme, but the little jump after each change makes it look soo buggy :(

![ezgif-3-c9e2068eb9](https://github.com/Nerwyn/material-rounded-theme/assets/78862555/a27f3ab5-67f6-468e-a999-3e6ed45ede68)

**Comment by Nerwyn** [comment]
I think it's because of how I was setting view styles, which was causing them to be lost and reapplied every time the view changed. Can you try the 2.0.2 beta and see if that fixes it? It seems to fix it for me.

**Comment by xvlw** [comment]
Just tested 2.0.2 beta and the jumping for me is gone. Huge improvement, thank you!

**Comment by currydani** [comment]
Fixed it for me too, thank you so much!

**Comment by Nerwyn** [comment]
Fixed in [2.0.2](https://github.com/Nerwyn/material-rounded-theme/releases/tag/2.0.2)
