### ISSUE TITLE
Seperate Dark/Light Themes

### ISSUE THREAD

**Issue by currydani** [Nerwyn/material-rounded-theme#23]
I love the theme and got it in use on all my devices! But on my wallpanels, there is no dark mode and i can only toggle dark/light mode with browser mod, which is kind of buggy sometimes. Would it be possible to get the theme as additional dark/light version that can be set with the default theme service and can be easier applied with automations to devices without the dark/light mode choosen by the device itself?

**Comment by Nerwyn** [comment]
There are dark and light modes.
![image](https://github.com/Nerwyn/material-rounded-theme/assets/43071698/d55dbfe0-b6c8-4dd5-90fc-fdc3fe761155)
Do the dark and light toggles not appear in user browser settings?

**Comment by Nerwyn** [comment]
What if you set the theme using the services developer tool?
![image](https://github.com/Nerwyn/material-rounded-theme/assets/43071698/2a47de5c-7005-4e9f-a4df-6132c967245d)

**Comment by currydani** [comment]
The service sadly only sets the backend mode to the dark mode, if the user sets the device to dark mode for example. It just means you can set different themes for dark and light mode. But you can not set the device to a different mode with a service or automation, as long as the theme supports both modes. My workaround was to copy a theme and remove the light/dark part of the file and rename it "rounded dark" and "rounded light". It works, but every time a update or change with the theme happens, it breaks the copies.

![Screenshot_20240710_091714_Home Assistant](https://github.com/Nerwyn/material-rounded-theme/assets/78862555/8e649fe1-d1e7-4c78-837c-1df5404f01d6)

**Comment by Nerwyn** [comment]
Do the light/dark mode options just not appear at all on the user profile on your tablets? I'm confused as to why it wouldn't be available since even my crappy old Fire tablet 7 has that option available and it can barely run Fully Kiosk Browser with Home Assistant.

**Comment by currydani** [comment]
They do appear, but I can't use the automatic mode, because the tablet doesn't have a dark mode systemwise. If I set it to auto, light or dark it stays like that forever. There is no way to switch the browser between light and dark remotely to follow day/night cycle without a android dark mode. And the service call only applies the chosen theme to the light/dark mode in the backend, so it is ready if you decide to switch the mode in the user settings to light or dark. It is actually a fire tablet, try putting yours into auto mode, it will not change to dark at night or after the service call.

**Comment by Nerwyn** [comment]
@currydani I've added separating out the light and dark themes for all themes to the build pipeline, if you could check if it works for your use cases.

**Comment by currydani** [comment]
Amazing, thats exactly what i meant! Thank you so much!

**Comment by Nerwyn** [comment]
Added in [2.1.0](https://github.com/Nerwyn/material-rounded-theme/releases/tag/2.1.0).
