### ISSUE TITLE
Place the navigation bar at the top of dashboard subviews.

### ISSUE THREAD

**Issue by ZOXSOCKS** [Nerwyn/material-rounded-theme#24]
**Is your feature request related to a problem? Please describe.**
As this theme is inspired by the Google Home app, having the back button/exit button at the top left of sub-views would make the overall experience more intuitive and alike to the Google Home app. Currently, because of the global nav bar adjustment, the back button appears at the bottom of the screen alongside the page title.

**Describe the solution you'd like**
Allow the navigation bar to appear at the top of each sub-view page, along with the sub-view title, and remove the shading on the navigation bar.

**Additional context**
You can also see that the navigation bar on Home Assistant is shaded, whereas in the screenshot in Google Home, there’s no background to that navigation bar.

![image](https://github.com/user-attachments/assets/89851ee7-b411-41a0-895c-ece9891d6bf9)

![image](https://github.com/user-attachments/assets/109330b4-e59c-406c-a01c-93a8de5ec2fd)

<3

**Comment by Nerwyn** [comment]
Try the 2.1.0 beta! Turns out it was easy to implement.

**Comment by Nerwyn** [comment]
Wait it's broken in edit mode.

**Comment by Nerwyn** [comment]
Alright 2.1.0 beta 3 behaves as expected in and out of edit mode and the subview toolbar doesn't interfere with it's cards.

**Comment by ZOXSOCKS** [comment]
![Screenshot_20240729-083307](https://github.com/user-attachments/assets/d298a035-8840-44fc-8d99-54aef75f4dce)

That's worked beautifully! Thank you so much!

**Comment by Nerwyn** [comment]
Fixed in [2.1.0](https://github.com/Nerwyn/material-rounded-theme/releases/tag/2.1.0).
