### ISSUE TITLE
Navigation Bar not respecting safe area

### ISSUE THREAD

**Issue by etiennelenhart** [Nerwyn/material-rounded-theme#26]
**Checklist:**

-   [x] I updated to the latest version available
-   [x] I cleared the cache of my browser

**Release with the issue:**
2.1.0
**Last working release (if known):**
unknown
**Browser and Operating System:**
Home Assistant Companion App on iOS 17.6.1

**Description of problem:**
Somehow the Navigation Bar at the bottom doesn’t seem to take `safe-area-insets` into account.

![IMG_0822](https://github.com/user-attachments/assets/24f706c7-a370-4d9f-81cb-94f4d9070c9b)

**Javascript errors shown in the web inspector (if applicable):**

```

```

**Additional information:**
I’m new to Home Assistant and just set this up so I don’t know if this was working before. Judging from the screenshots in the readme, it probably did.

**Comment by Nerwyn** [comment]
You're right, I didn't account for safe area insets in the new padding calculations for the header, footer, and view.
![image](https://github.com/user-attachments/assets/ca118ee7-708e-41df-9969-c4e1e44fa2ee)
Let me see if I can fix that.

**Comment by Nerwyn** [comment]
@etiennelenhart Can you try the 2.1.1 beta?

**Comment by etiennelenhart** [comment]
Nice, thank you for the rapid fix. Working perfectly in the latest beta version.

**Comment by Nerwyn** [comment]
Fixed in [2.1.1](https://github.com/Nerwyn/material-rounded-theme/releases/tag/2.1.1)
