### ISSUE TITLE
Edge distances are different to the HA theme?

### ISSUE THREAD

**Issue by fugazzy** [Nerwyn/material-rounded-theme#28]
Today I found this theme and I do like it very much: The optic is very nice and it was always my whish to have the titlebar on the bottom.
I recently redesigned my dashboard to fit on iPhone, iPad and desktop and I also use the new badges (HA2024.8) on the top now.

Now I noticed one problem with this new theme:
The distances to right and left edges of the screen seem to be different than in the HA theme and that leads to changes in my layout, specially on my iPhone (the most narrow sceen)
![IMG_3730](https://github.com/user-attachments/assets/9555fcc7-ab68-4ab3-8373-b8e62249e889)
![IMG_3731](https://github.com/user-attachments/assets/8c967f6f-6557-47a1-89d1-66c69412c8c6)

**Comment by Nerwyn** [comment]
Per the README: 

> Adds a 12px margin to each side of the view to match the Google Home app.

That's intentional.
