### ISSUE TITLE
MIssing color

### ISSUE THREAD

**Issue by MathiasSvDK** [Nerwyn/material-rounded-theme#31]
Why doesn't it have the second color on the actions etc?
![Skærmbillede 2024-09-16 185742](https://github.com/user-attachments/assets/7e0c5d65-dcb1-428a-941b-7b5f8d0c7bba)

**Comment by Nerwyn** [comment]
It does for me. You didn't use the bug report template and are missing actionable information. What browser and operating system is this on? How does it look in the default theme?

**Comment by MathiasSvDK** [comment]
Hi. 
Sorry.

From the dev tools, it uses this for the background:
--bg-color: rgba(var(--rgb-primary-text-color), 1)

On the default theme it looks.. default.
<img width="512" alt="Screenshot 2024-09-18 at 09 25 34" src="https://github.com/user-attachments/assets/d26b777c-ef43-4407-9102-3dbdb5025f94">

I use chrome but tried Arc, safari and chrome and the app.
I am on mac.

**Comment by Nerwyn** [comment]
Which version of Home Assistant are you on? It doesn't use those vars for my devices.

**Comment by MathiasSvDK** [comment]
The latest. Just updated last night but it was also a problem before that

ons. 18. sep. 2024 kl. 14.04 skrev Nerwyn ***@***.***>:

**Comment by Nerwyn** [comment]
For my built in tile features the background color is `var(--control-button-background-color)`, which is equal to `var(--disabled-color)`, which is defined in the theme.

Can you try the 2.1.4 beta? I've set `--bg-color` to `--disabled-color`.

**Comment by MathiasSvDK** [comment]
Didn't work sadly.
I'm using mushroom if that does anything? From the images it looked like you do too.

**Comment by Nerwyn** [comment]
I'm not using Mushroom, I'm using [my custom features project](https://github.com/Nerwyn/service-call-tile-feature).

**Comment by Nerwyn** [comment]
Unfortunately this is an issue with how Mushroom Card sets feature background colors and doesn't follow theme values. You'll have to make an issue on that repo.
