### ISSUE TITLE
Navigation Bar how to make like images

### ISSUE THREAD

**Issue by platini76** [Nerwyn/material-rounded-theme#34]
hello, I search everywhere in card mod and in this repo. I did not find any examples to have a navigation bar that substitute top bar like the one in photos example... can you help me ?

**Comment by Nerwyn** [comment]
You should just have to install card-mod, install this theme, and then set this theme as the user theme. What does it look like for you now?

**Comment by platini76** [comment]
card-mod installed.
module installed.
theme is on... but top bar is on the top

<img width="669" alt="Screenshot 2024-10-07 alle 22 08 36" src="https://github.com/user-attachments/assets/451b858e-ac0e-4432-8887-bd1399ca7910">

**Comment by Nerwyn** [comment]
It looks like you set the theme for the view, not the user. You need to set it for the user profile.

![Screenshot_20241007-165845.png](https://github.com/user-attachments/assets/c70165ba-4bdb-4960-9433-696a2e457ca2)

**Comment by platini76** [comment]
ohhh got now.. it works only as user theme? not as dasboard theme?

**Comment by Nerwyn** [comment]
If you want the theme to apply to elements outside of the view you have to set it at the user level. Setting the theme at the view level (which is what you were doing) only affects the view. You have to set the theme at the user level to have it apply to the toolbar elements.

> it is possible to reduce with on bottom bar?

I do not understand your question.

**Comment by platini76** [comment]
sorry I was not clear on last question: it is possible to reduce the bottom bar height?

**Comment by Nerwyn** [comment]
[This variable](https://github.com/Nerwyn/material-rounded-theme/blob/main/src/material_rounded/theme.yaml#L59) in the theme sets the footer height. You may have to adjust the surrounding CSS [in this file](https://github.com/Nerwyn/material-rounded-theme/blob/main/src/common/root.css). Finally you have to recompile all of it into a Home Assistant theme file using [this script](https://github.com/Nerwyn/material-rounded-theme/blob/main/githooks/pre-commit.py).

**Comment by platini76** [comment]
thank you... too difficult for a noob like me... but thanks very very much.. for your kindness in replies! a hugg!
