### ISSUE TITLE
No background colour on light theme

### ISSUE THREAD

**Issue by iamthekings5** [Nerwyn/material-rounded-theme#35]
**Checklist:**

- [/] I updated to the latest version available
-   [/] I cleared the cache of my browser (Using android companion app)

**Release with the issue: v2.1.4**

**Last working release (if known):**

**Browser and Operating System:**

Android Companion App Android 14 OneUI 6.1

**Description of problem:**

On the Android companion app, using the light theme the entities blend in with the white background making it visually unappealing. It is difficult to describe the problem but I believe if shown alongside the dark theme it is clear what the issue is.
![Screenshot_20241021_163032_Home Assistant.png](https://github.com/user-attachments/assets/fd19fea2-b193-4f5c-a7b0-f10cdbe4ad83)

![Screenshot_20241021_163018_Home Assistant.png](https://github.com/user-attachments/assets/427309d7-8abf-4210-8f8b-6366204c4f84)
Notice how for the dark theme even when switches are off or it is an entity there is a dark background contrasting it whereas it is just white for the light theme.

I am using bubble card in a vertical stack.

**Javascript errors shown in the web inspector (if applicable):**

```

```

**Additional information:**

**Comment by Nerwyn** [comment]
There's not much I can do about which theme colors custom cards use without making something in Home Assistant look incorrect. In this case I can change light mode `--secondary-background-color` to something other than pure white, but I can't do anything about the icon color being too light without change the theme accent color.

Try the 2.1.5 beta. It changes the light mode secondary background color.

**Comment by Nerwyn** [comment]
You could also use bubble card's build in style options to change the background and icon colors.
