### ISSUE TITLE
Profile Picture gets covered when selecting profile in sidebar

### ISSUE THREAD

**Issue by iamthekings5** [Nerwyn/material-rounded-theme#37]
**Checklist:**

-   [/] I updated to the latest version available
-   [/] I cleared the cache of my browser

**Release with the issue: v2.1.5**

**Last working release (if known):**

**Browser and Operating System: Home Assistant Companion App Android 14 OneUI 6.1**

**Description of problem:**

When you select the current user in bottom left of Home Assistant in the sidebar the profile picture gets covered by the accent colour.

![Screenshot_20241023_104841_Home Assistant.png](https://github.com/user-attachments/assets/ccdde747-8e27-48fd-8453-bc06fbb06d64)

**Javascript errors shown in the web inspector (if applicable):**

```

```

**Additional information:**

**Comment by Nerwyn** [comment]
![image](https://github.com/user-attachments/assets/3df51e76-2b02-49c6-af98-c4ef086b055a)

It doesn't seem to be a problem for me on desktop or the Android companion app. Was this an issue in 2.1.4? None of the styles that fix the profile pic layer was touched for this patch.

**Comment by iamthekings5** [comment]
> ![image](https://github.com/user-attachments/assets/3df51e76-2b02-49c6-af98-c4ef086b055a)
> 
> It doesn't seem to be a problem for me on desktop or the Android companion app. Was this an issue in 2.1.4? None of the styles that fix the profile pic layer was touched for this patch.

Hi,

I didn't use 2.1.4 so I'm not sure. I don't have a profile picture set, may that be why?

**Comment by Nerwyn** [comment]
It could be the lack of profile picture. I'll test that later today and will fix it if it is.

**Comment by Nerwyn** [comment]
[Fixed in 2.1.6](https://github.com/Nerwyn/material-rounded-theme/releases/tag/2.1.6). Nice catch!
