### ISSUE TITLE
Automations Blending in with background issue

### ISSUE THREAD

**Issue by iamthekings5** [Nerwyn/material-rounded-theme#39]
**Checklist:**

-   [/] I updated to the latest version available
-   [/] I cleared the cache of my browser

**Release with the issue:**
v2.1.6
**Last working release (if known):**

**Browser and Operating System:**
Android Companion App Android 14 OneUI 6.1

**Description of problem:**
When setting up an automation the actions are blending in with the background.
![Screenshot_20241024_140513_Home Assistant.png](https://github.com/user-attachments/assets/49607e73-c5f8-46ca-a5c4-068130e7073f)

**Javascript errors shown in the web inspector (if applicable):**

```

```

**Additional information:**

**Comment by Nerwyn** [comment]
This is the same issue as #36 but I get what you mean. I probably could set the card border color to be the same as the lovelace background color. That would give this some contrast without changing how views look.

**Comment by Nerwyn** [comment]
@iamthekings5 try the 2.1.7 alpha build.

**Comment by Nerwyn** [comment]
Tbh I don't think I'm a fan of how this looks, and think the blended embedded `ha-card`s look better than the borders.

**Comment by iamthekings5** [comment]
I think the borders being black might look better but I'm not aware of the constraints you are facing with regards to the views. I'll leave the implementation decision up to you.

**Comment by Nerwyn** [comment]
I'm going to opt not to change this.

We're limited in what we can change with Home Assistant themes. Card mod does greatly increase our ability to modify things, but with an edge case like this adding a border here makes it look worse (IMO) in most other places.
