### ISSUE TITLE
sideways scrolling in bottom bar

### ISSUE THREAD

**Issue by Xornop** [Nerwyn/material-rounded-theme#4]
I have about 8 pages in my dashboard. Would be nice if sideways scrolling was possible, since they all get squished together in the bottom bar on the companion app now.
It's default behaviour in the app without this theme

**Comment by Nerwyn** [comment]
Can you try [1.4.1-beta.001](https://github.com/Nerwyn/material-rounded-theme/releases/tag/1.4.1-beta.001)? It should fix this issue along with the current view icon cutting off the edit mode buttons.

**Comment by Xornop** [comment]
@Nerwyn 
Works in 1.4.1-beta.002, however: the buttons are as wide as their icon, or name if they have one. 
This also makes the buttons have different widths instead of being evenly spaced out.
There is also no spacing between the names or icons.

**Comment by Nerwyn** [comment]
Thanks for the feedback. I'll need to figure out a way to make all view buttons the same width even when name length is different, and add padding to the names and icons.

**Comment by Nerwyn** [comment]
@Xornop can you try the latest beta (1.4.1-beta.003)? I've tweaked it a lot and now views have a minimum width of 52px, and they should all be the same size now. I've also added padding, word wrap, and overflow ellipses to view labels.

**Comment by Xornop** [comment]
It's pretty good now, but it already starts wrapping the titles if they're more than 5 characters, reducing the title to 3 chars. Maybe increase the width per tab?

**Comment by Nerwyn** [comment]
Can you share a screenshot? It isn't wrapping prematurely on my devices.

**Comment by Nerwyn** [comment]
Ah wait it's probably due to your personal text zoom settings. I need to find a way to make this text ignore user preferences like the Google Home app does, or at least be less affected by it.

**Comment by Nerwyn** [comment]
I've made a few changes to try to mitigate this in the latest beta:
- Font size is now the minimum of 13px or 3% of screen width.
- View label padding reduced to 1px on each side.
- View tab width is now the minimum of 72px or scaled to fit five view tabs.
- Removed text overflow ellipsis since it is often more annoying than helpful.

Unfortunately it looks like the Android app is ignoring CSS variables like `text-size-adjust`, so the best I can do is the above. Let me know how it looks @Xornop!

**Comment by Nerwyn** [comment]
I've reduced the size of the menu buttons on the sides of the toolbar which should also provide more space for the view buttons and labels.

**Comment by Nerwyn** [comment]
@Xornop if there's no further feedback I'm going to go ahead and release this.

**Comment by Nerwyn** [comment]
Released [1.5.1](https://github.com/Nerwyn/material-rounded-theme/releases/tag/1.5.1)
