### ISSUE TITLE
In a subview, the icon bar space remains

### ISSUE THREAD

**Issue by xitters** [Nerwyn/material-rounded-theme#40]
In a subview, if a 1-card panel is added, the icon bar space remains, can this be solved?
![1](https://github.com/user-attachments/assets/ef8aa898-e9e7-4a43-9edc-7a4dd69ad7c0)

**Comment by Nerwyn** [comment]
Good catch! Let me see if I can do anything about that.

**Comment by Nerwyn** [comment]
@xitters try the 2.1.7 alpha. Fixing it turned out to be easier than expected.

**Comment by Nerwyn** [comment]
Although I'm not sure if I should make the bottom have no padding or padding to match the sides. Let me double check what the default theme does.

**Comment by Nerwyn** [comment]
Default theme does no padding. Let me know if you think I should do no padding on the bottom of subviews or make it match the sides.

**Comment by xitters** [comment]
Its perfect!
![image](https://github.com/user-attachments/assets/14fef743-d19c-471e-b635-9b4c9e0bb282)

**Comment by xitters** [comment]
I think , no padding, like the default theme does.

**Comment by xitters** [comment]
I love the look of your theme by the way! Thanks a lot
![image](https://github.com/user-attachments/assets/c34df72f-6da2-43e6-9ccf-433c09139cfa)

**Comment by Nerwyn** [comment]
[Fixed in 2.1.7](https://github.com/Nerwyn/material-rounded-theme/releases/tag/2.1.7)

**Comment by kooikerseth** [comment]
It appears that this fix also removed the padding on 1-card panels that are not subviews. I am using the Frigate card and wanted to add it as a second tab but the bottom of the card then gets hidden behind the bottom bar.

**Comment by kooikerseth** [comment]
You know what, It may be an issue with the frigate card instead (or could be either?) Not sure what info it may be grabbing, but testing with another card, all is working as expected.... hmmmm 
![image](https://github.com/user-attachments/assets/0d9ff5c7-3102-4edd-8b20-b33f98ab56c6)
