### ISSUE TITLE
Dark graphics and difficult to interpret

### ISSUE THREAD

**Issue by fernandolcardoso** [Nerwyn/material-rounded-theme#41]
**Is your feature request related to a problem? Please describe.**
I would like to suggest a change in the colors of the graphics, as the visibility is poor and difficult to interpret

![image](https://github.com/user-attachments/assets/a30e90eb-03fb-404a-a84b-44659831f871)

**Describe the solution you'd like**
I think that inverse colors, as in the case of the dark theme, would be interesting if white or similar

**Comment by fernandolcardoso** [comment]
Here are some suggested colors that I believe will provide better visibility.

![image](https://github.com/user-attachments/assets/bd1b0883-1518-4d22-b33c-053edb6667f7)

**Comment by Nerwyn** [comment]
@fernandolcardoso try the 2.1.9 alpha. I managed to change it to the theme primary color and brighten the stroke color.

![image](https://github.com/user-attachments/assets/df56d16d-3966-4b52-8c7d-e1424b5338d5)

Unfortunately it doesn't apply if the graph takes a long time to load.

**Comment by fernandolcardoso** [comment]
Thanks for the feedback, unfortunately it didn't work for me

![image](https://github.com/user-attachments/assets/1e5ce5ba-c0af-4fb8-a1f0-faf9fb172a76)


![image](https://github.com/user-attachments/assets/e3d28faf-a2c1-4359-87e4-91503ea80724)

**Comment by Nerwyn** [comment]
Does switching view tabs change anything? What if you create a view with just one graph.

To clarify those are entity cards with a graph footer right?

**Comment by Nerwyn** [comment]
@fernandolcardoso? If the fixes I've made don't work for you then there's nothing more I can do.

**Comment by Nerwyn** [comment]
[Should be fixed in 2.1.9](https://github.com/Nerwyn/material-rounded-theme/releases/tag/2.1.9). If it isn't fix for you after updating and ensuring that the card-mod changes are working, I don't think there's much more I can do.
