### ISSUE TITLE
No dashboard background on 2024.11 HA release

### ISSUE THREAD

**Issue by cziter15** [Nerwyn/material-rounded-theme#42]
**Checklist:**
-   [x] I updated to the latest version available
-   [x] I cleared the cache of my browser

**Browser and Operating System:**
- Win 11, latest Chrome
- Kubuntu 24, latest Firefox
- Android, Chrome

**Description of problem:**

- Some of my dashboards have a background image and it was working earlier.
- After updating HA to 2024.11, the dashboard background immediately changes to gray or white.
- **IMPORTANT: No mod variants are not affected.**

**Comment by Nerwyn** [comment]
It looks like they changed how background images are set, but I think I have a fix. Try the 2.1.9 alpha.

**Comment by Nerwyn** [comment]
[Fixed in 2.1.9](https://github.com/Nerwyn/material-rounded-theme/releases/tag/2.1.9)
