### ISSUE TITLE
No mod, only for lovelace bar

### ISSUE THREAD

**Issue by xitters** [Nerwyn/material-rounded-theme#47]
Hello, is it possible not to apply the mod only to the bar? since I put a ticker with news below, but I would like to continue keeping the mod
![Sin título](https://github.com/user-attachments/assets/1007c20d-109c-4ba2-a0b3-2b3c95667e2a)

**Comment by xitters** [comment]
Or that you can change the location of the bar above, it would be a very good option

**Comment by xitters** [comment]
I already changed the location of the ticker above, so I don't make you work haha. But it would be a good option maybe not to apply the mod only to the bar
![Sin títudlo](https://github.com/user-attachments/assets/ea11d3e0-dc3e-4691-9767-5f5f28404d9b)

**Comment by Nerwyn** [comment]
If you want some card-mod changes but not others, you need to modify the theme source files and rebuild it with Python as described [here in the README](https://github.com/Nerwyn/material-rounded-theme?tab=readme-ov-file#developing-modifying-and-building-the-theme).

The CSS changes for the toolbar are found in [root.css](https://github.com/Nerwyn/material-rounded-theme/blob/2.1.10/src/common/root.css) and [view.css](https://github.com/Nerwyn/material-rounded-theme/blob/2.1.10/src/common/view.css). You can selectively disable or delete styles from these two and other files and then run [build.sh](https://github.com/Nerwyn/material-rounded-theme/blob/2.1.10/build.sh) (or the Python command to run githooks/precommit.py within it) to build the theme file. Then you have to copy the built theme file to your Home Assistant instance and run the action `frontend.reload_themes` from the [HA actions dev tool](http://homeassistant.local:8123/developer-tools/action).
