### ISSUE TITLE
Broken "Material Rounded" theme?

### ISSUE THREAD

**Issue by doubleangels** [Nerwyn/material-rounded-theme#5]
**Checklist:**

-   [X ] I updated to the latest version available
-   [ X] I cleared the cache of my browser

**Release with the issue:** 1.5.1

**Last working release (if known):**

**Browser and Operating System:** Android HA App/Chrome/Firefox

**Description of problem:** When using the "Material Rounded No Mod" theme, icons are displayed fine. When using the normal "Material Rounded" theme, icons do not appear. With the normal theme, the card-mod features does not appear to work. 

![Screenshot_20240301-013830](https://github.com/Nerwyn/material-rounded-theme/assets/9072542/d7c2c8ea-bb5a-4010-b836-f9589e8faa98)
![Screenshot_20240301-013900](https://github.com/Nerwyn/material-rounded-theme/assets/9072542/db4eee27-51b8-402f-b841-92f3df887ad2)

**Javascript errors shown in the web inspector (if applicable):**

```
Nothing is shown as an error in Chrome web inspector.
```

**Additional information:** This issue appears in Chrome/Firefox on my desktop and in Chrome on Android as well as the the HA app. All are latest versions.

**Comment by Nerwyn** [comment]
It's not broken on my devices (Windows Brave/Firefox, Android HA app/Firefox, and iPhone HA app). I'm not sure why the card-mod version would affect the tile icons. Are you on the latest version of card-mod? Are you sure that you completely cleared cache?

**Comment by doubleangels** [comment]
After a little more investigation, it seems like this is some sort of issue with the [Material Symbols](https://github.com/beecho01/material-symbols) icon set that I'm using. This doesn't seem to occur with the default HA icons.

**Comment by doubleangels** [comment]
The card-mod features work for me when installing manually, but not when installed through HACS.

**Comment by Nerwyn** [comment]
Extra weird since Material Symbols shouldn't be affected by this and is working just fine for me.

Did you try closing, stopping, and reopening the app? You're not using the no mod version of the theme right?

**Comment by doubleangels** [comment]
Yes, I am using the mod version of the theme. I'm beginning to think something is just wrong with my HA install, haha. I will try the Material Symbols when installed manually and not through HACS (as that worked for both big-slider-card and card-mod) and report back.

**Comment by doubleangels** [comment]
Installing Material Symbols completely breaks my big-slider-card install. Weird.

**Comment by Nerwyn** [comment]
@doubleangels if there's nothing actionable from my end I'm going to go ahead and close this card.
