### ISSUE TITLE
Notification Counter in for Settings in Sidebar Missing Border

### ISSUE THREAD

**Issue by iamthekings5** [Nerwyn/material-rounded-theme#51]
**Checklist:**

-   [/] I updated to the latest version available
-   [/] I cleared the cache of my browser

**Release with the issue:**
v8.2.0

**Last working release (if known):**
The version before the big material you reimplementation

**Browser and Operating System:**
HA Companion App (Android), Google Chrome (Windows), Microsoft Edge (Windows)

**Description of problem:**
![image](https://github.com/user-attachments/assets/93e65180-7c35-4735-9b52-078e418d68e0)
From my memory, prior to the big material you reimplementation, there was a circular border around the number 1. I usually use `custom-sidebar` but I have removed it to ensure the issue occurs without it and can confirm the issue is present by default. I cannot remember if within the circular border if `var(--primary-color)` or `var(--accent-color)` was used (i.e. if the colour was supposed to match exactly the colour of when an item in the sidebar is selected, as shown in the screenshot).

I am currently using Material Rounded and the issue was identified there, but I have tested Material You briefly and have noticed the same issue.

**Javascript errors shown in the web inspector (if applicable):**

```

```

**Additional information:**

**Comment by Nerwyn** [comment]
[Per the README](https://github.com/Nerwyn/material-rounded-theme?tab=readme-ov-file#navigation-drawer)

The navigation drawer and rail badge colors have been updated to match the material design 3 specification.
