### ISSUE TITLE
Dashboard background not visible in HA 2025.1.0 beta

### ISSUE THREAD

**Issue by coolssor** [Nerwyn/material-rounded-theme#52]
**Checklist:**

-   [X] I updated to the latest version available
-   [X] I cleared the cache of my browser

**Release with the issue:** 3.0.0 and 3.0.1-alpha.001

**Last working release (if known):** 3.0.0 with HA 2024.12.5

**Browser and Operating System:** Android using Companion, unable to test desktop currently

**Description of problem:**
The new HA release (2025.1.0b1) adds additional functionality for dashboard backgrounds, such as transparency, scroll/fixed positions, sizing, etc. This appears to not be compatible with Material Rounded Theme (and Material You Theme).

The image background set manually on the view flashes for a moment, then switches to the default coloured background set by the theme. This isn't present when selecting the default Home Assistant theme. Here is a screen recording showing the behaviour: https://imgur.com/a/dMXzQuP

**Javascript errors shown in the web inspector (if applicable):**

```
N/A
```

**Additional information:**
N/A

**Comment by Nerwyn** [comment]
Once this issue is present in the HA release version, I'll work on a fix!

**Comment by Nerwyn** [comment]
@coolssor the latest alpha might fix it. As part of some style tweaks I removed the explicit setting of view background, which may have caused the issue in the first place.

**Comment by coolssor** [comment]
> @coolssor the latest alpha might fix it. As part of some style tweaks I removed the explicit setting of view background, which may have caused the issue in the first place.

That did the trick, thanks very much for your assistance 😁

**Comment by Nerwyn** [comment]
[Fixed in 3.0.1.](https://github.com/Nerwyn/material-rounded-theme/releases/tag/3.0.1)
