### ISSUE TITLE
Some color schemes don't apply the right color to the navigation bar and status bar

### ISSUE THREAD

**Issue by MathisP75** [Nerwyn/material-rounded-theme#53]
As seen in your own screenshots, some color schemes make it so that the navigation bar at the bottom has the wrong color. The same applies to the status bar. From what I can see, it seems to happen when the base color is green/teal.
![image](https://github.com/user-attachments/assets/3365cbe5-985e-4a19-9a70-43c6715e5eaf)
![Screenshot_20241224-153755](https://github.com/user-attachments/assets/e9e5549e-1042-4eaf-b336-9b451b9bd724)

**Comment by Nerwyn** [comment]
This is actually an issue with the Home Assistant app. It determines the status and navigation bar colors on app launch, and does not update them based on subsequent changes. The material color theme is applied after the `home-assistant` element loads, which is after the app retrieves the app and navigation bar colors.

Additionally, the app doesn't support [defining these colors with anything other than explicit values](https://companion.home-assistant.io/docs/integrations/theming/), which means that we likely can't fix this.

I'll leave this open and play around with possible solutions later, but it likely isn't fixable.

**Comment by Nerwyn** [comment]
Calling `frontend.reload_themes` fixes the issue. I think I can update the JS module resource to call this, but I'll also have to prevent it from causing an infinite loop since the module re-applies theme colors on theme changes.

**Comment by Nerwyn** [comment]
Calling `frontend.reload_themes` every time the user colors are applied is not great. But I dug around the [Android](https://github.com/home-assistant/android/blob/master/app/src/main/java/io/homeassistant/companion/android/webview/WebViewActivity.kt#L835C51-L835C88) and [iOS](https://github.com/home-assistant/iOS/blob/6d641e806ec61f4f5b9aaaad3dedf8fdb63905bc/Sources/App/WebView/WebViewExternalMessageHandler.swift#L99-L100) companion app code and found that I should be able to use `window.PostMessage` to trigger updating of the bar colors.

**Comment by Nerwyn** [comment]
[Here's the correct way to send messages to the Home Assistant companion app external bus.](https://github.com/home-assistant/frontend/blob/704e7f279fe3b41aa3d1f73caa7399738c948e17/src/external_app/external_messaging.ts#L403-L414) This works WAY better than calling the reload themes service and doesn't affect other instances of Home Assistant.

I've pushed the fix to the [dev branch here](https://github.com/Nerwyn/material-rounded-theme/blob/dev/dist/material-rounded-theme.js). Are you using the CDN version or a local version of the file? Can you update your local copy or try using [the dev CDN version](https://cdn.jsdelivr.net/gh/nerwyn/material-rounded-theme@dev/dist/material-rounded-theme.js) and see if it fixes it on your end too? Make sure to thoroughly clear cache!

**Comment by MathisP75** [comment]
I am using a local version, will test tomorrow. Thanks a lot, I love this theme!

**Comment by MathisP75** [comment]
After updating the file, force stopping the Home Assistant app and clearing the cache, it seems to work consistently! Thank you!

**Comment by Nerwyn** [comment]
Fixed in [3.0.1](https://github.com/Nerwyn/material-rounded-theme/releases/tag/3.0.1), although the module has to be redownloaded for non-CDN users.
