### ISSUE TITLE
Material You accent color is not applied when changed

### ISSUE THREAD

**Issue by Mesya82** [Nerwyn/material-rounded-theme#56]
**Checklist:**

-   [x] I updated to the latest version available
-   [x] I cleared the cache of my browser

**Release with the issue:**
3.0.0

**Last working release (if known):**

**Browser and Operating System:**
HA Companion app 2024.12.1-full
Pixel 9 Pro, Android 15 (AP4A.241205.013)

**Description of problem:**
The accent color used for Material You color pallette is not always changes whenever it is changed in the system. It can take up to 48 hours for it to actually get an actual one (and in that time it will change 2 times already because the wallpaper is changed every 24 hours)

**Javascript errors shown in the web inspector (if applicable):**

```

```

**Additional information:**

**Comment by Nerwyn** [comment]
How are you defining/changing the material color sensor? It changes instantaneously for me when the states of my sensors change.

Are you talking about the accent color sensor of your companion app? You may have to increase your companion app sensor update frequency in the app settings.

**Comment by Mesya82** [comment]
I've just checked it, and yeah - it is not updated. But shouldn't it update every 15 minutes? But, I guess, that's more of a companion app problem, rather than a theme

**Comment by Nerwyn** [comment]
I just checked and this appears to be a bug with the companion app. Force stopping, clearing companion app cache, and toggling the sensor in the companion app settings seems to update it but that's not a good solution. I'd create a bug on [this repository](https://github.com/home-assistant/android).
